[package]
name = "resonite-manager"
version = "0.1.1"
edition = "2021"
authors = ["kokoa-love"]
description = "Kokoa Resonite Tools - CLI tool for Resonite management"

[dependencies]
clap = "2.33"  # コマンドライン引数のパース
regex = "1.5"  # 正規表現
resonite-tools-lib = { path = "../lib" }  # 内部ライブラリ
