name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './cli -> target'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./gui

      - name: Check Tauri icon
        run: |
          if (!(Test-Path ".\gui\src-tauri\icons\icon.ico")) {
            Write-Error "Icon file not found: .\gui\src-tauri\icons\icon.ico"
            exit 1
          }
          Write-Host "Icon file found: .\gui\src-tauri\icons\icon.ico"
        shell: pwsh

      # Build CLI
      - name: Build CLI (release)
        run: cargo build --release -p resonite-manager

      # Build GUI with Tauri
      - name: Build GUI (release)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          projectPath: ./gui
          tagName: ${{ github.ref_name }}
          releaseName: 'Kokoa Resonite Tools ${{ github.ref_name }}'
          releaseBody: |
            # Kokoa Resonite Tools ${{ github.ref_name }}
            
            ## 📦 ダウンロード
            
            ### GUI版（推奨）
            - **Windows**: `Resonite.Tools_${{ github.ref_name }}_x64_en-US.msi` または `.exe`
            
            ### CLI版
            - **Windows**: `resonite-manager-${{ github.ref_name }}-windows.exe`
            
            ## 🚀 新機能・変更点
            
            このリリースの詳細については、[CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) をご確認ください。
            
            ## 📋 システム要件
            
            - Windows 10/11 (x64)
            - .NET 8.0 Runtime（DepotDownloader用）
            - 十分なディスク容量（Resoniteインストール用）
            
            ## 🔧 使用方法
            
            ### GUI版
            1. `.msi` または `.exe` ファイルをダウンロード
            2. インストーラーを実行
            3. 初回セットアップガイドに従って設定
            
            ### CLI版
            1. `resonite-manager-${{ github.ref_name }}-windows.exe` をダウンロード
            2. コマンドラインから実行
            
            ## ⚠️ 注意事項
            
            - 初回起動時にDepotDownloaderが自動ダウンロードされます
            - セキュリティソフトが反応する場合がありますが、安全なツールです
            - Steam Guardが有効な場合、初回ダウンロード時に認証が必要です
          releaseDraft: false
          prerelease: false
          includeDebug: false
          includeRelease: true

      # Create CLI release asset
      - name: Create CLI Release Asset
        run: |
          cp ./target/release/resonite-manager.exe ./resonite-manager-${{ github.ref_name }}-windows.exe
        
      - name: Upload CLI binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./resonite-manager-${{ github.ref_name }}-windows.exe
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}