name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './cli -> target'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./gui

      - name: Check Tauri icon
        run: |
          if (!(Test-Path ".\gui\src-tauri\icons\icon.ico")) {
            Write-Error "Icon file not found: .\gui\src-tauri\icons\icon.ico"
            exit 1
          }
          Write-Host "Icon file found: .\gui\src-tauri\icons\icon.ico"
        shell: pwsh

      # Build CLI
      - name: Build CLI (release)
        run: cargo build --release -p resonite-manager

      # Build raw executable first for portable version
      - name: Build GUI executable (for portable)
        run: |
          cd gui
          npm run tauri build -- --bundles none
        
      # Build GUI with Tauri
      - name: Build GUI (release)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          projectPath: ./gui
          tagName: ${{ github.ref_name }}
          releaseName: 'Kokoa Resonite Tools ${{ github.ref_name }}'
          releaseBody: |
            # Kokoa Resonite Tools ${{ github.ref_name }}
            
            ## 📦 ダウンロード
            
            ### GUI版（推奨）
            - **インストーラー**: `Kokoa.Resonite.Tools_${{ github.ref_name }}_x64_en-US.msi` - 自動インストール・更新対応
            - **セットアップEXE**: `Kokoa.Resonite.Tools_${{ github.ref_name }}_x64-setup.exe` - 軽量インストーラー
            - **ポータブル版**: `kokoa-resonite-tools-${{ github.ref_name }}-windows-portable.exe` - インストール不要のシングルバイナリ
            
            ### CLI版
            - **Windows**: `resonite-manager-${{ github.ref_name }}-windows.exe`
            
            ## 🚀 新機能・変更点
            
            このリリースの詳細については、[CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) をご確認ください。
            
            ## 📋 システム要件
            
            - Windows 10/11 (x64)
            - .NET 8.0 Runtime（DepotDownloader用）
            - 十分なディスク容量（Resoniteインストール用）
            
            ## 🔧 使用方法
            
            ### GUI版
            1. **インストーラー版**: `.msi`ファイルをダウンロードして実行
            2. **ポータブル版**: `.exe`ファイルをダウンロードして任意の場所で実行
            3. 初回セットアップガイドに従って設定
            
            ### CLI版
            1. `resonite-manager-${{ github.ref_name }}-windows.exe` をダウンロード
            2. コマンドラインから実行
            
            ## ⚠️ 注意事項
            
            - 初回起動時にDepotDownloaderが自動ダウンロードされます
            - セキュリティソフトが反応する場合がありますが、安全なツールです
            - Steam Guardが有効な場合、初回ダウンロード時に認証が必要です
          releaseDraft: false
          prerelease: false
          includeDebug: false
          includeRelease: true

      # Create additional release assets
      - name: Create CLI Release Asset
        run: |
          cp ./target/release/resonite-manager.exe ./resonite-manager-${{ github.ref_name }}-windows.exe
        
      - name: Create GUI Portable Binary
        run: |
          # Check multiple possible locations for the Tauri executable
          $possiblePaths = @(
            ".\gui\src-tauri\target\release\resonite-tools-tauri.exe",
            ".\gui\src-tauri\target\release\kokoa-resonite-tools.exe",
            ".\gui\src-tauri\target\release\bundle\nsis\Kokoa Resonite Tools_*_x64-setup.exe",
            ".\gui\src-tauri\target\release\bundle\msi\*.msi"
          )
          
          # First try to find the raw executable
          $foundExecutable = $null
          if (Test-Path ".\gui\src-tauri\target\release\resonite-tools-tauri.exe") {
            $foundExecutable = ".\gui\src-tauri\target\release\resonite-tools-tauri.exe"
          } elseif (Test-Path ".\gui\src-tauri\target\release\kokoa-resonite-tools.exe") {
            $foundExecutable = ".\gui\src-tauri\target\release\kokoa-resonite-tools.exe"
          } else {
            # Try to extract from NSIS bundle
            $nsisFiles = Get-ChildItem ".\gui\src-tauri\target\release\bundle\nsis\" -Filter "*setup.exe" -ErrorAction SilentlyContinue
            if ($nsisFiles) {
              Write-Host "Found NSIS installer: $($nsisFiles[0].FullName)"
              # For now, we'll copy the NSIS installer as the portable version
              # In a real scenario, you'd want to extract the exe from the installer
              $foundExecutable = $nsisFiles[0].FullName
            }
          }
          
          if ($foundExecutable) {
            cp $foundExecutable .\kokoa-resonite-tools-${{ github.ref_name }}-windows-portable.exe
            Write-Host "Created portable version from: $foundExecutable"
          } else {
            Write-Host "Searching for files in target directories..."
            if (Test-Path ".\gui\src-tauri\target\release") {
              Write-Host "Files in .\gui\src-tauri\target\release:"
              Get-ChildItem ".\gui\src-tauri\target\release" -Recurse -Name | Select-Object -First 20
            }
            if (Test-Path ".\gui\src-tauri\target\release\bundle") {
              Write-Host "Files in .\gui\src-tauri\target\release\bundle:"
              Get-ChildItem ".\gui\src-tauri\target\release\bundle" -Recurse -Name | Select-Object -First 20
            }
            Write-Warning "GUI executable not found, skipping portable version"
          }
        shell: pwsh
        
      - name: Upload additional binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./resonite-manager-${{ github.ref_name }}-windows.exe
            ./kokoa-resonite-tools-${{ github.ref_name }}-windows-portable.exe
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}